### PR TITLE
Added missing string to id.json

### PR DESCRIPTION
**Pull request by Tamsy**

### CODE REVIEW

**Review by ngocjohn — COMMENTED** [review]
Please edit the key to "illuminated", thanks

**Comment by Tamsy** [comment]
> Please edit the key to "illuminated", thanks

Done.

**Comment by ngocjohn** [comment]
Hi @Tamsy I've added new font styling options in UI editor. Could I ask you to update the missing strings translations for these options? Just make a new PR with updated files, thanks! 

CleanShot 2024-08-24 at 16 28 31

**Comment by Tamsy** [comment]
> Hi @Tamsy I've added new font styling options in UI editor. Could I ask you to update the missing strings translations for these options? Just make a new PR with updated files, thanks!
> 
> CleanShot 2024-08-24 at 16 28 31

All done (for German & Indonesian).

**Pull request merged**
